package edu.handong.csee.java.Lab09;
/**
 * 
 * @author s0rrow
 *
 */
public class Salesman {// This method is for getting and setting names and sales of each salesman.
	private String mName;// Declare local string variable for getting name of salesman.
	private double mSales;// Declare local double variable for getting sales of salesman.
	
	public String getmName() {// A getter method generated by Eclipse.
		return mName;// Get string variable mName from this class.
	}
	public void setmName(String mName) {// A setter method generated by Eclipse.
		this.mName = mName;// Assign given parameter mName to local variable mName from this class.
	}
	public double getmSales() {// A getter method generated by Eclipse.
		return mSales;// Get double variable mSales from this class.
	}
	public void setmSales(double mSales) {// A setter method generated by Eclipse.
		this.mSales = mSales;// Assign given parameter mSales to local variable mSales from this class.
	}
}
